Feature NXP-27737 deploy management api on separate port
nuxeo/nuxeo-management-rest-api pull request #11
Opened 2019-08-23 17:52 UTC by kevinleturc

2019-08-23 17:52 UTC, nuxeojenkins commented
[View issue in JIRA](https://jira.nuxeo.com/browse/NXP-27737)

2019-08-23 18:09 UTC, efge requested changes

2019-08-23 18:09 UTC, efge commented on nuxeo-management-rest-api/src/main/java/org/nuxeo/rest/management/ManagementFilter.java
> +    protected static final ThreadLocal<Boolean> API_ENABLED = ThreadLocal.withInitial(() -> FALSE);
You don't need an initial value, you can just have `TRUE` or `null` as values.

2019-08-23 18:09 UTC, efge commented on nuxeo-management-rest-api/src/main/java/org/nuxeo/rest/management/ManagementFilter.java
> +            API_ENABLED.set(FALSE);
You can do `API_ENABLED.remove()` here, which has the benefit of early cleanup of the thread-local.

2019-08-23 18:09 UTC, efge commented on nuxeo-management-rest-api/src/test/java/org/nuxeo/rest/management/TestManagementFilter.java
> +package org.nuxeo.rest.management;
Missing copyright header

2019-08-26 09:53 UTC, troger approved these changes

2019-08-26 10:13 UTC, efge approved these changes

2019-08-26 10:13 UTC, merged